#!/usr/bin/env node
/**
 * emit-twin-data.mts
 * 
 * Generates public/twin-data.js from SeededReevesDataSource at build time.
 * Injects window.__TWIN_DATA__ with the seeded well data for the mockup to consume.
 */

import { writeFileSync, mkdirSync, readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { mapWellAtomsToViewModels } from '../src/data/mapping.js';
import type { FixtureFile } from '../src/types/atoms';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const projectRoot = join(__dirname, '..');
const outputPath = join(projectRoot, 'public', 'twin-data.js');

async function main() {
  console.log('Generating public/twin-data.js from SeededReevesDataSource...');
  
  // Load fixture files from filesystem
  const fixtureFiles = [
    join(projectRoot, 'fixtures', 'reeves-wells-01.json'),
    join(projectRoot, 'fixtures', 'reeves-wells-02.json'),
    join(projectRoot, 'fixtures', 'reeves-wells-03.json')
  ];
  
  const loadedFixtures = fixtureFiles.map(path => {
    const content = readFileSync(path, 'utf-8');
    return JSON.parse(content) as FixtureFile;
  });
  
  // Merge all fixtures
  const fixtureData = {
    wells: loadedFixtures.flatMap(f => f.wells),
    productionTimeseries: loadedFixtures.flatMap(f => f.productionTimeseries),
    rrcLeases: loadedFixtures.flatMap(f => f.rrcLeases),
    revenueAllocationUnits: loadedFixtures.flatMap(f => f.revenueAllocationUnits),
    equipmentStates: loadedFixtures.flatMap(f => f.equipmentStates)
  };
  
  // Map to view models
  const wells = mapWellAtomsToViewModels(
    fixtureData.wells,
    fixtureData.productionTimeseries,
    fixtureData.equipmentStates
  );
  
  // Reeves County clusters (from SeededReevesDataSource.getClusters())
  const clusters = [
    { name: 'North Reeves', lng: -103.620, lat: 31.720, radiusMi: 8, padDensity: 0.45, sev: 1.15 },
    { name: 'Central Reeves', lng: -103.665, lat: 31.680, radiusMi: 7, padDensity: 0.50, sev: 1.10 },
    { name: 'East Reeves', lng: -103.580, lat: 31.755, radiusMi: 6, padDensity: 0.40, sev: 1.05 },
    { name: 'West Reeves', lng: -103.705, lat: 31.635, radiusMi: 7, padDensity: 0.38, sev: 1.20 },
    { name: 'Northeast Reeves', lng: -103.540, lat: 31.790, radiusMi: 5, padDensity: 0.35, sev: 1.00 }
  ];
  
  // Timeline events (from SeededReevesDataSource.getTimelineEvents())
  const timelineEvents = [
    { day: 3,  type: 'workover', label: 'ESP swap · North Reeves',      detail: 'STATE REEVES A 3H, restored 185 BOE/d' },
    { day: 7,  type: 'anomaly',  label: 'Pressure spike · Central Reeves', detail: '4 wells flagged, monitoring' },
    { day: 10, type: 'workover', label: 'Tubing repair · East Reeves',  detail: 'STATE REEVES C 2H, +95 BOE/d' },
    { day: 14, type: 'failure',  label: 'Rod parted · West Reeves',     detail: 'STATE REEVES D 1H down, workover scheduled' },
    { day: 17, type: 'weather',  label: 'Dust storm · Reeves County',   detail: 'Brief curtailment, all wells recovered' },
    { day: 21, type: 'workover', label: 'Pump retrofit · North Reeves', detail: 'STATE REEVES A 7H, +120 BOE/d' },
    { day: 25, type: 'anomaly',  label: 'Communication loss · Central Reeves', detail: '3 wells recalibrated' },
    { day: 28, type: 'workover', label: 'ESP replacement · East Reeves', detail: 'STATE REEVES C 4H, +155 BOE/d' }
  ];
  
  // Cause breakdown (from SeededReevesDataSource.getCauseBreakdown())
  const causeBreakdown = [
    { id: 'surface_equipment',   pct: 18 },
    { id: 'artificial_lift',     pct: 22 },
    { id: 'reservoir_pressure',  pct: 9 },
    { id: 'completion_geometry', pct: 13 },
    { id: 'healthy',             pct: 38 }
  ];
  
  // Region label for Reeves County
  const regionLabel = "Reeves County · Permian Basin";
  
  // Overlay panels that should show "OPERATOR OVERLAY · SEEDED" badges
  const overlayPanels = [
    "equipment_health",
    "sensor_reliability", 
    "well_communication",
    "pressure_anomaly"
  ];
  
  // Generate the JavaScript file content
  const jsContent = `// Auto-generated by scripts/emit-twin-data.mts
// DO NOT EDIT THIS FILE MANUALLY - it will be overwritten at build time

// Source selection with URL param override
(function() {
  const params = new URLSearchParams(window.location.search);
  const sourceParam = params.get('source');
  window.__TWIN_SOURCE__ = sourceParam === 'synthetic' ? 'synthetic' : 'seeded';
})();

// Seeded operator data from Reeves County fixtures
window.__TWIN_DATA__ = ${JSON.stringify({
  wells,
  clusters,
  timelineEvents,
  causeBreakdown,
  regionLabel,
  overlayPanels
}, null, 2)};
`;
  
  // Ensure public directory exists
  mkdirSync(join(projectRoot, 'public'), { recursive: true });
  
  // Write the file
  writeFileSync(outputPath, jsContent, 'utf-8');
  
  console.log(`✓ Generated public/twin-data.js`);
  console.log(`  - ${wells.length} wells`);
  console.log(`  - ${clusters.length} clusters`);
  console.log(`  - ${timelineEvents.length} timeline events`);
  console.log(`  - Region: ${regionLabel}`);
}

main().catch(err => {
  console.error('Failed to generate twin-data.js:', err);
  process.exit(1);
});
